name: myfirstapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  google_sign_in: ^4.5.6
  flutter_riverpod: ^0.12.0
  flutter_signin_button: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/