name: myfirstapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#pub-------------------------------------
  flutter_riverpod: ^1.0.3

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.2.4

  google_sign_in: ^4.5.6
  flutter_signin_button: ^2.0.0

  image_picker: ^0.8.4+4

  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"


#-----------------------------------------


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/